MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_backbone"
  #WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  WEIGHTS: "/root/Mask2Former/output/try2/model_0004999.pth"
  PIXEL_MEAN: [124.574, 97.684, 65.202]
  PIXEL_STD: [51.273, 45.172, 34.660]
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used
DATASETS:
  TRAIN: ("panoptic_train_with_sem_seg",)
  TEST: ("panoptic_val_with_sem_seg",)  # to evaluate instance and semantic performance as well
OUTPUT_DIR: "/root/Mask2Former/output/try2"
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  #STEPS: (327778, 355092)
  MAX_ITER: 368750
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  IMAGE_SIZE: 1024
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "mask_former_panoptic"
TEST:
  EVAL_PERIOD: 5000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
VERSION: 2
